#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "RASER 2D"
	printf "\n\t%-9s  %-40s"  "0.2"       "RASER 3D" 
	printf "\n\t%-9s  %-40s"  "0.3"       "RASER LGAD"
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    "RASER 2D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.1.2"    "RASER 2D scan for time resolution" 
	printf "\n\t%-5s  %-40s\n"  "0.1.3"    "data processing 2D" 
	printf "\n\t%-5s  %-40s\n"  "0.1.4"    "get time resolution 2D" 
}
usage_0_2() { 
    printf "\n\t%-5s  %-40s\n"  "0.2.1"    "RASER 3D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.2.2"    "RASER 3D scan for time resolution" 
	printf "\n\t%-5s  %-40s\n"  "0.2.3"    "Batch background operation voltage scan" 
	printf "\n\t%-5s  %-40s\n"  "0.2.4"    "data processing voltage scan" 
	printf "\n\t%-5s  %-40s\n"  "0.2.5"    "get time resolution voltage scan" 
	printf "\n\t%-5s  %-40s\n"  "0.2.6"    "Stop Batch background operation" 
}
usage_0_3() { 
    printf "\n\t%-5s  %-40s\n"  "0.3.1"    "RASER 2D LGAD" 
	printf "\n\t%-5s  %-40s\n"  "0.3.2"    "RASER 2D PIN"
	printf "\n\t%-5s  %-40s\n"  "0.3.3"    "RASER 2D LGAD p_type"
}
if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
	number=$2  
	t_number=$3
	n_step=$4 
	m_p=$5   
fi

sub_0_1(){
Time=2021_5_28
case $option in 
    0.1.1) echo "raser 2D SiC basic information..."
		python3 python/raser.py 2D  
    	;;
    0.1.2) echo "raser 2D scan for time resolution..."
		mkdir out/fenics_${time_gap}/ -p
		rm out/fenics_${time_gap}/*
		python3 python/raser.py 2D_scan out/fenics_${time_gap}/
    	;;
	0.1.3) echo "data processing"
		mkdir result/sic_${time_gap}_result/ -p
		rm result/sic_${time_gap}_result/*
		python3 python/raser_read_sample.py out/fenics_${time_gap}/ result/sic_${time_gap}_result/ V
		;;
	0.1.4) echo "get time resolution"
		mkdir result/root -p
		python3 python/add_noise_raser.py result/sic_${time_gap}_result/ result/root/sic_${time_gap}_result.root
		esac
}
 
sub_0_2(){
time_gap=2021_6_18_3D_gap_scan
time_voltage=2021_6_18_3D_voltage_scan

case $option in 
    0.2.1) echo "raser 3D SiC basic information..."
		mkdir fig/ -p
		singularity exec raser.simg python3 python/raser_3D.py 3D  
    	;;
    0.2.2) echo "raser 3D scan for time resolution..."
		mkdir out/fenics_${time_gap}/ -p
		python3 python/raser_3D.py 3D_scan out/fenics_${time_gap} ${number} ${t_number} ${n_step} ${m_p}
    	;;
	0.2.3) echo "Batch background operation voltage scan"
		mkdir out/fenics_${time_voltage}/ -p
		python3 python/run_job.py 2000 10000 -650 5
		;;
	0.2.4) echo "data processing voltage scan"
		mkdir result/sic_${time_voltage}_result/gap_40_voltage_650.0 -p	
		# rm result/sic_${time_gap}_result/*
		singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-650.0 result/sic_${time_voltage}_result/gap_40_voltage_650.0/ V
		;;
	0.2.5) echo "get time resolution voltage scan"
		mkdir result/voltage/root -p
		singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_650.0/ result/voltage/root/sic_${time_voltage}_650_result.root
		;;
	0.2.6) echo "Stop Batch background operation"
		singularity instance stop --all
		esac
}

sub_0_3(){
Time=2021_5_28
case $option in 
    0.3.1) echo "raser 2D lgad electric field..."
		python3 python/raser_lgad.py LGAD
    	;;
	0.3.2) echo "raser 2D pin electric field..."
		python3 python/raser_lgad.py PIN
    	;;
	0.3.3) echo "raser 2D P_type lgad electric field map"
		python3 python/raser_lgad.py LGAD_P_type
		;;
		esac
}




case $option in 
   0.1) echo "RASER 2D"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "RASER 2D"
        sub_0_1 option
        ;;
   0.2) echo "RASER 3D"
        usage_0_2
        echo "Please enter your option: " 
        read option 
        sub_0_2 option 
        ;;
    0.2.*) echo "RASER 3D"
        sub_0_2 option 
		;;
   0.3) echo "RASER 2D"
        usage_0_3
        echo "Please enter your option: " 
        read option 
        sub_0_3 option 
        ;;
    0.3.*) echo "RASER 2D"
        sub_0_3 option 
		esac