#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "KDetSim" 
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    "raser 2D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.1.2"    "raser 2D scan for time resolution" 
	printf "\n\t%-5s  %-40s\n"  "0.1.2"    "data processing" 
	printf "\n\t%-5s  %-40s\n"  "0.1.2"    "get time resolution" 
}

if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1    
fi



sub_0_1(){
Time=2021_5_28
case $option in 
    0.1.1) echo "raser 2D SiC basic information..."
		python3 python/raser.py 2D  
    	;;
    0.1.2) echo "raser 2D scan for time resolution..."
		mkdir out/fenics_${Time}/ -p
		rm out/fenics_${Time}/*
		python3 python/raser.py 2D_scan out/fenics_${Time}/
    	;;
	0.1.3) echo "data processing"
		mkdir result/sic_${Time}_result/ -p
		rm result/sic_${Time}_result/*
		python3 python/raser_read_sample.py out/fenics_${Time}/ result/sic_${Time}_result/ V
		;;
	0.1.4) echo "get time resolution"
		mkdir result/root -p
		python3 python/add_noise_raser.py result/sic_${Time}_result/ result/root/sic_${Time}_result.root
		esac
}
 



case $option in 
   0.1) echo "Raser"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "Raser"
        sub_0_1 option
        ;;
        
esac
