#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "RASER" 
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    "RASER 2D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.1.2"    "RASER 2D scan for time resolution" 
	printf "\n\t%-5s  %-40s\n"  "0.1.3"    "data processing 2D" 
	printf "\n\t%-5s  %-40s\n"  "0.1.4"    "get time resolution 2D" 
}
usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.2.1"    "RASER 3D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.2.2"    "RASER 3D scan for time resolution" 
	printf "\n\t%-5s  %-40s\n"  "0.2.3"    "data processing 3D" 
	printf "\n\t%-5s  %-40s\n"  "0.2.4"    "get time resolution 3D" 
	printf "\n\t%-5s  %-40s\n"  "0.2.5"    "Batch background operation" 
}
if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
	number=$2  
	t_number=$3
	n_step=$4   
fi

sub_0_1(){
Time=2021_5_28
case $option in 
    0.1.1) echo "raser 2D SiC basic information..."
		python3 python/raser.py 2D  
    	;;
    0.1.2) echo "raser 2D scan for time resolution..."
		mkdir out/fenics_${Time}/ -p
		rm out/fenics_${Time}/*
		python3 python/raser.py 2D_scan out/fenics_${Time}/
    	;;
	0.1.3) echo "data processing"
		mkdir result/sic_${Time}_result/ -p
		rm result/sic_${Time}_result/*
		python3 python/raser_read_sample.py out/fenics_${Time}/ result/sic_${Time}_result/ V
		;;
	0.1.4) echo "get time resolution"
		mkdir result/root -p
		python3 python/add_noise_raser.py result/sic_${Time}_result/ result/root/sic_${Time}_result.root
		esac
}
 
sub_0_2(){
Time=2021_6_8_3D

case $option in 
    0.2.1) echo "raser 3D SiC basic information..."
		mkdir fig/ -p
		python3 python/raser_3D.py 3D  
    	;;
    0.2.2) echo "raser 3D scan for time resolution..."
		mkdir out/fenics_${Time}/ -p
		python3 python/raser_3D.py 3D_scan out/fenics_${Time}/ ${number} ${t_number} ${n_step}
    	;;
	0.2.3) echo "data processing"
		mkdir result/sic_${Time}_result/ -p
		rm result/sic_${Time}_result/*
		python3 python/raser_read_sample.py out/fenics_${Time}/ result/sic_${Time}_result/ V
		;;
	0.2.4) echo "get time resolution"
		mkdir result/root -p
		python3 python/add_noise_raser.py result/sic_${Time}_result/ result/root/sic_${Time}_result.root
		;;
	0.2.5) echo "Batch background operation"
		# mkdir out/fenics_${Time}/ -p
		python3 python/run_job.py 100 10000
		esac
}
 
case $option in 
   0.1) echo "RASER 2D"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "RASER 2D"
        sub_0_1 option
        ;;

   0.2) echo "RASER 3D"
        usage_0_2
        echo "Please enter your option: " 
        read option 
        sub_0_2 option 
        ;;
    0.2.*) echo "RASER 3D"
        sub_0_2 option   
esac
